name: Pketh writes ＿φ(°-°=)
description: On building softwarey things.
url: http://pketh.github.io
markdown: redcarpet
highlighter: pygments
paginate: 4
paginate_path: "blog/page:num"
gems:
  - jemoji
